import React from 'react';
import { Order } from '../types';
import { useApp } from '../context/AppContext';
import { getServiceModeText } from '../i18n/translations';
import { FileText, Printer, CheckCircle, ShieldCheck, Download, X } from 'lucide-react';

interface InvoiceModalProps {
  order: Order;
  onClose: () => void;
}

export const InvoiceModal: React.FC<InvoiceModalProps> = ({ order, onClose }) => {
  const { language, t } = useApp();

  const handlePrint = () => {
    window.print();
  };

  const invoiceTitles = {
    hy: {
      modalTitle: 'Էլեկտրոնային Անդորրագիր & Հաշիվ',
      print: 'Տպել',
      tagline: 'Հավաստագրված ծառայությունների մարքեթփլեյս',
      paidReleased: 'Վճարված է',
      escrowHeld: 'Էսքրոու պահված',
      invoiceNo: 'Հաշիվ #',
      client: 'Հաճախորդ',
      specialist: 'Մասնագետ / Կատարող',
      serviceCol: 'Ծառայության անվանում',
      modeCol: 'Տեսակ',
      amountCol: 'Գումար',
      calloutFee: 'Մոտեցման (Callout) վճար',
      onSiteVisit: 'Տեղում այց',
      paymentMethod: 'Վճարման եղանակ',
      onlineEscrow: 'Առցանց Էսքրոու (Քարտով)',
      cash: 'Կանխիկ տեղում',
      platformCommission: 'Հարթակի կոմիսիոն մասհանում',
      specialistNetEarnings: 'Մասնագետի զուտ եկամուտ',
      totalPayable: 'Ընդհանուր վճարման գումար',
      footerNote: 'Այս փաստաթուղթը գեներացվել է ինքնաշխատ կարգով Varpet PWA հարթակի կողմից: Բոլոր իրավունքները պաշտպանված են:',
      downloadPrint: 'Ներբեռնել / Տպել',
      close: 'Փակել',
    },
    ru: {
      modalTitle: 'Электронный чек и квитанция',
      print: 'Печать',
      tagline: 'Маркетплейс проверенных услуг',
      paidReleased: 'Оплачено',
      escrowHeld: 'Удержано на эскроу',
      invoiceNo: 'Счет #',
      client: 'Клиент',
      specialist: 'Мастер / Исполнитель',
      serviceCol: 'Наименование услуги',
      modeCol: 'Тип',
      amountCol: 'Сумма',
      calloutFee: 'Стоимость выезда (Callout)',
      onSiteVisit: 'Выездной визит',
      paymentMethod: 'Способ оплаты',
      onlineEscrow: 'Онлайн Эскроу (Картой)',
      cash: 'Наличными на месте',
      platformCommission: 'Комиссия платформы',
      specialistNetEarnings: 'Чистый доход мастера',
      totalPayable: 'Итого к оплате',
      footerNote: 'Данный документ сформирован автоматически платформой Varpet PWA. Все права защищены.',
      downloadPrint: 'Скачать / Печать',
      close: 'Закрыть',
    },
    en: {
      modalTitle: 'Electronic Receipt & Invoice',
      print: 'Print',
      tagline: 'Verified Services Marketplace',
      paidReleased: 'Paid & Released',
      escrowHeld: 'Held in Escrow',
      invoiceNo: 'Invoice #',
      client: 'Customer',
      specialist: 'Specialist / Provider',
      serviceCol: 'Service Description',
      modeCol: 'Mode',
      amountCol: 'Amount',
      calloutFee: 'Callout Fee',
      onSiteVisit: 'On-site Visit',
      paymentMethod: 'Payment Method',
      onlineEscrow: 'Online Escrow (Card)',
      cash: 'Cash on Delivery',
      platformCommission: 'Platform Commission Fee',
      specialistNetEarnings: 'Specialist Net Earnings',
      totalPayable: 'Total Payable Amount',
      footerNote: 'This document was automatically generated by the Varpet PWA platform. All rights reserved.',
      downloadPrint: 'Download / Print',
      close: 'Close',
    },
  };

  const str = invoiceTitles[language] || invoiceTitles.hy;

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white w-full max-w-2xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden my-8 animate-in fade-in zoom-in-95 duration-200">
        {/* Modal Top Bar */}
        <div className="px-6 py-4 bg-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-400" />
            <span className="font-semibold text-base">{str.modalTitle}</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="p-1.5 hover:bg-slate-800 text-slate-300 hover:text-white rounded-lg transition-colors flex items-center gap-1 text-xs"
            >
              <Printer className="w-4 h-4" />
              {str.print}
            </button>
            <button
              onClick={onClose}
              className="p-1.5 hover:bg-slate-800 text-slate-400 hover:text-white rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Content */}
        <div className="p-8 space-y-6 text-slate-800" id="printable-invoice">
          {/* Header */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center pb-6 border-b border-slate-200 gap-4">
            <div>
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center text-lg">
                  V
                </div>
                <span className="text-xl font-bold tracking-tight text-slate-900">VARPET PLATFORM</span>
              </div>
              <p className="text-xs text-slate-500 mt-1">{str.tagline}</p>
            </div>
            <div className="text-left sm:text-right">
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                <CheckCircle className="w-3.5 h-3.5" />
                {order.paymentStatus === 'paid_released' ? str.paidReleased : str.escrowHeld}
              </span>
              <div className="text-sm font-semibold text-slate-900 mt-1">{str.invoiceNo}{order.orderNumber}</div>
              <div className="text-xs text-slate-500">
                {new Date(order.createdAt).toLocaleDateString(language === 'hy' ? 'hy-AM' : language === 'ru' ? 'ru-RU' : 'en-US')}
              </div>
            </div>
          </div>

          {/* Parties */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 bg-slate-50 p-4 rounded-xl border border-slate-100 text-sm">
            <div>
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                {str.client}
              </span>
              <div className="font-semibold text-slate-900">{order.customerName}</div>
              <div className="text-slate-600 text-xs mt-0.5">{order.customerPhone}</div>
              <div className="text-slate-600 text-xs mt-0.5">{order.customerAddress}</div>
            </div>
            <div>
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                {str.specialist}
              </span>
              <div className="font-semibold text-slate-900">{order.specialistName || (language === 'ru' ? 'Мастер' : language === 'en' ? 'Specialist' : 'Վարպետ')}</div>
              <div className="text-slate-600 text-xs mt-0.5">{order.specialistPhone}</div>
              <div className="text-slate-600 text-xs mt-0.5">{order.specialistWorkingAddress || 'Երևան, Հայաստան'}</div>
            </div>
          </div>

          {/* Line items table */}
          <div>
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b border-slate-200 text-xs font-semibold text-slate-500 uppercase">
                  <th className="py-3">{str.serviceCol}</th>
                  <th className="py-3 text-center">{str.modeCol}</th>
                  <th className="py-3 text-right">{str.amountCol}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                <tr>
                  <td className="py-3.5">
                    <div className="font-medium text-slate-900">{order.serviceName}</div>
                    <div className="text-xs text-slate-500 max-w-sm truncate">{order.problemDescription || (language === 'ru' ? 'Стандартное обслуживание' : language === 'en' ? 'Standard service' : 'Ստանդարտ սպասարկում')}</div>
                  </td>
                  <td className="py-3.5 text-center text-xs text-slate-600">
                    {getServiceModeText(order.serviceMode, language)}
                  </td>
                  <td className="py-3.5 text-right font-medium text-slate-900">
                    {order.basePrice.toLocaleString()} ֏
                  </td>
                </tr>
                {order.calloutFee > 0 && (
                  <tr>
                    <td className="py-3 text-slate-700">{str.calloutFee}</td>
                    <td className="py-3 text-center text-xs text-slate-500">{str.onSiteVisit}</td>
                    <td className="py-3 text-right font-medium text-slate-900">
                      {order.calloutFee.toLocaleString()} ֏
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Total & commission breakdown */}
          <div className="pt-4 border-t border-slate-200 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div className="text-xs text-slate-500 space-y-1">
              <div className="flex items-center gap-1.5 text-slate-600 font-medium">
                <ShieldCheck className="w-4 h-4 text-blue-600" />
                {str.paymentMethod}՝ {order.paymentMethod === 'online_escrow' ? str.onlineEscrow : str.cash}
              </div>
              <div>{str.platformCommission}՝ {(order.commissionRate * 100).toFixed(0)}% ({order.commissionAmount.toLocaleString()} ֏)</div>
              <div>{str.specialistNetEarnings}՝ {order.specialistEarnings.toLocaleString()} ֏</div>
            </div>

            <div className="bg-slate-100 px-6 py-3 rounded-xl text-right w-full sm:w-auto">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider block">{str.totalPayable}</span>
              <span className="text-2xl font-bold text-blue-700">{order.totalAmount.toLocaleString()} ֏</span>
            </div>
          </div>

          {/* Footer notice */}
          <div className="pt-6 border-t border-slate-100 text-center text-xs text-slate-400">
            {str.footerNote}
          </div>
        </div>

        {/* Modal Bottom Actions */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-200 rounded-lg transition-colors"
          >
            {str.close}
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors flex items-center gap-2 shadow-xs"
          >
            <Download className="w-4 h-4" />
            {str.downloadPrint}
          </button>
        </div>
      </div>
    </div>
  );
};

